version: "3.7"
services:
    web:
        image: nginx
        hostname: web
        container_name: web
        domainname: web.local
        ports:
            - "80:80"
        volumes:
            - ./sample-app:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
        networks:
            sample_app_network:
                aliases:
                    - web.local
        links:
            - php

    php:
        image: php:fpm
        hostname: php
        container_name: php
        volumes:
            - ./sample-app:/code
        networks: 
            - sample_app_network

networks:
    sample_app_network: